---
- name: "Развёртывание Redmine с SQLite"
  hosts: all
  become: true

  tasks:
    - name: "Установка Docker"
      ansible.builtin.include_role:
        name: geerlingguy.docker
      tags:
        - prepare-servers

    - name: "Создать директорию для Redmine"
      ansible.builtin.file:
        path: "{{ redmine_opt_folder }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      tags:
        - install-redmine

    - name: "Создать .env файл конфигурации"
      ansible.builtin.template:
        src: env.j2
        dest: "{{ redmine_opt_folder }}/.env"
        owner: root
        group: root
        mode: "0600"
      tags:
        - install-redmine

    - name: "Запустить контейнер Redmine с SQLite"
      community.docker.docker_container:
        name: redmine
        image: redmine:6.0
        state: started
        restart_policy: unless-stopped
        ports:
          - "{{ redmine_port }}:3000"
        env_file: "{{ redmine_opt_folder }}/.env"
        volumes:
          - "redmine_files:/usr/src/redmine/files"
          - "redmine_db:/usr/src/redmine/db"
        labels:
          com.datadoghq.tags.service: "redmine"
          com.datadoghq.tags.env: "development"
      tags:
        - install-redmine

  handlers:
    - name: "Restart redmine"
      community.docker.docker_container:
        name: redmine
        state: restarted

  roles:
    - role: geerlingguy.pip
      tags:
        - prepare-servers
    - role: geerlingguy.docker
      tags:
        - prepare-servers